# Site settings
title: Christophe Benoist
subtitle: Technical Program Manager
email: christophe.benoist@gmail.com
description: Technical Program Manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cben0ist.github.io" # the base hostname & protocol for your site
author: Christophe benoist
street_address: 128 Lansdowne Ave
city: Toronto
state: "ON"
zip_code: M6K2V9
country: Canada
phone: Phone? Where we're going, we don't need phones.

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: https://github.com/cben0ist
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/cben0ist/
linkedin_url: https://www.linkedin.com/in/christophebenoist/
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/CBen0ist

# Build settings
markdown: kramdown
